name = "server-control-hub"
main = "src/index.js"
compatibility_date = "2026-08-14"

# Create a D1 database named server-control and replace the placeholder below.
[[d1_databases]]
binding = "DB"
database_name = "server-control"
database_id = "111c6398-9f08-4109-b510-1c799078c6c0"

