name: Promote beta 13

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-beta13.yml"

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Make release latest
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit v2.0.0-beta.13 --repo "${GITHUB_REPOSITORY}" --latest
